# Generated by Django 5.0.2 on 2025-11-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblSchool',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('school_code', models.CharField(max_length=32, unique=True)),
                ('school_name', models.CharField(blank=True, max_length=500, null=True)),
                ('school_mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('school_contactnos', models.TextField(blank=True, null=True)),
                ('school_email', models.CharField(blank=True, max_length=255, null=True)),
                ('school_website', models.CharField(blank=True, max_length=500, null=True)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('school_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('school_country_id', models.IntegerField(blank=True, null=True)),
                ('school_state_id', models.IntegerField(blank=True, null=True)),
                ('school_city_id', models.IntegerField(blank=True, null=True)),
                ('school_profile_photo', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TblSchool',
            },
        ),
        migrations.CreateModel(
            name='TblGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblGrade_school_id', to='adminweb.tblschool')),
            ],
            options={
                'db_table': 'TblGrade',
            },
        ),
        migrations.CreateModel(
            name='TblDivision',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('division_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblDivision_grade_id', to='adminweb.tblgrade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblDivision_school_id', to='adminweb.tblschool')),
            ],
            options={
                'db_table': 'TblDivision',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('user_code', models.CharField(max_length=32, unique=True)),
                ('user_firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('user_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_gender', models.IntegerField(blank=True, null=True)),
                ('user_mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('user_contactnos', models.TextField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_enrollment_date', models.DateField(blank=True, null=True)),
                ('user_profilephoto', models.TextField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=255, null=True)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TblUser',
                'indexes': [models.Index(fields=['user_code'], name='TblUser_user_co_9830c1_idx'), models.Index(fields=['user_role'], name='TblUser_user_ro_24cb67_idx'), models.Index(fields=['is_deleted'], name='TblUser_is_dele_a0435c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TblTeacherAcademics',
            fields=[
                ('teacheracademic_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_type', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAcademics_division_id', to='adminweb.tbldivision')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAcademics_grade_id', to='adminweb.tblgrade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAcademics_school_id', to='adminweb.tblschool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAcademics_user_id', to='adminweb.tbluser')),
            ],
            options={
                'db_table': 'TblTeacherAcademics',
                'indexes': [models.Index(fields=['user'], name='TblTeacherA_user_id_a9a299_idx'), models.Index(fields=['school'], name='TblTeacherA_school__f6abdf_idx'), models.Index(fields=['grade'], name='TblTeacherA_grade_i_9b43ea_idx'), models.Index(fields=['division'], name='TblTeacherA_divisio_5882dd_idx'), models.Index(fields=['subject'], name='TblTeacherA_subject_d07660_idx'), models.Index(fields=['academic_year'], name='TblTeacherA_academi_0bab52_idx'), models.Index(fields=['is_deleted'], name='TblTeacherA_is_dele_faa05f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TblStudentAcademics',
            fields=[
                ('studentacademic_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAcademics_division_id', to='adminweb.tbldivision')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAcademics_grade_id', to='adminweb.tblgrade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAcademics_school_id', to='adminweb.tblschool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAcademics_user_id', to='adminweb.tbluser')),
            ],
            options={
                'db_table': 'TblStudentAcademics',
                'indexes': [models.Index(fields=['user'], name='TblStudentA_user_id_3b424a_idx'), models.Index(fields=['school'], name='TblStudentA_school__dedcaf_idx'), models.Index(fields=['grade'], name='TblStudentA_grade_i_d1d7b3_idx'), models.Index(fields=['division'], name='TblStudentA_divisio_37a41d_idx'), models.Index(fields=['academic_year'], name='TblStudentA_academi_96bde3_idx'), models.Index(fields=['roll_no'], name='TblStudentA_roll_no_5002f6_idx'), models.Index(fields=['is_deleted'], name='TblStudentA_is_dele_a2ca8b_idx')],
            },
        ),
    ]
