# Generated by Django 5.2.8 on 2025-11-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_code', models.CharField(blank=True, max_length=32, null=True)),
                ('content_type', models.IntegerField(blank=True, null=True)),
                ('content_category', models.IntegerField(blank=True, null=True)),
                ('content_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TblContent',
            },
        ),
    ]
